import "dotenv/config";
import { getDb, disconnectDatabase } from "./client.js";

// ── Migration Runner ────────────────────────────────────────────────
//
// Applies pending migrations from the drizzle/ directory using the
// active database driver. The driver and connection URL are resolved
// from DB_DRIVER and DATABASE_URL environment variables.
//
// Usage:
//   npm run db:migrate
//
// Migrations are generated by drizzle-kit:
//   npm run db:generate
//

async function main(): Promise<void> {
  console.log("[migrate] Connecting to database...");
  const db = await getDb();

  console.log("[migrate] Running migrations...");

  // Drizzle's migrate() is driver-specific. Import the correct
  // migrator based on the active driver.
  const driverName = process.env.DB_DRIVER ?? "postgres";

  if (driverName === "postgres") {
    const { migrate } = await import("drizzle-orm/node-postgres/migrator");
    await migrate(db as never, { migrationsFolder: "drizzle" });
  } else if (driverName === "turso") {
    const { migrate } = await import("drizzle-orm/libsql/migrator");
    await migrate(db as never, { migrationsFolder: "drizzle" });
  } else {
    // Default to better-sqlite3 migrator
    const { migrate } = await import("drizzle-orm/better-sqlite3/migrator");
    migrate(db as never, { migrationsFolder: "drizzle" });
  }

  console.log("[migrate] Done");
  await disconnectDatabase();
}

main().catch((err: unknown) => {
  console.error("[migrate] Failed:", err);
  process.exit(1);
});
