import type { MigrationNotesInput, PrDescription } from "./types.js";
import type { PatchResult } from "../patcher/types.js";
import { summarizePatch } from "../patcher/patcher.js";

/**
 * Generate a PR title, body (with Migration Notes section), and branch name.
 *
 * Every Kiln-authored PR must:
 * - Cite ≥1 vendor changelog URL
 * - Name every breaking change by file:line that Kiln patched (or flagged)
 * - Flag cases that need human judgment explicitly
 */
export function buildPrDescription(input: MigrationNotesInput): PrDescription {
  const { packageName, fromVersion, toVersion, changelogUrl } = input;

  // Branch name: feat/kiln-<pkg>-<version>
  const branchName = `feat/kiln-${slugify(packageName)}-${toVersion}`;

  // PR title
  const title = buildTitle(input);

  // PR body
  const body = buildBody(input);

  const labels = buildLabels(input);

  return { title, body, branchName, labels };
}

function buildTitle(input: MigrationNotesInput): string {
  const { packageName, fromVersion, toVersion, groupedDeps } = input;

  if (groupedDeps && groupedDeps.length > 0) {
    const allPkgs = [packageName, ...groupedDeps.map((d) => d.packageName)];
    return `chore(deps): upgrade ${packageName} family (${allPkgs.length} packages) to ${toVersion}`;
  }

  return `chore(deps): upgrade ${packageName} ${fromVersion} → ${toVersion}`;
}

function buildBody(input: MigrationNotesInput): string {
  const {
    packageName,
    fromVersion,
    toVersion,
    changelogUrl,
    breakingChanges,
    patchResults,
    groupedDeps,
  } = input;

  const sections: string[] = [];

  // Summary
  sections.push(`## Summary\n`);
  if (groupedDeps && groupedDeps.length > 0) {
    const depList = [
      `- **${packageName}**: ${fromVersion} → ${toVersion}`,
      ...groupedDeps.map((d) => `- **${d.packageName}**: ${d.fromVersion} → ${d.toVersion}`),
    ].join("\n");
    sections.push(
      `Kiln grouped ${1 + groupedDeps.length} related dependency upgrades:\n\n${depList}`
    );
  } else {
    sections.push(
      `Kiln has upgraded **${packageName}** from \`${fromVersion}\` to \`${toVersion}\`.`
    );
  }

  // Changelog reference (required: ≥1 URL)
  sections.push(`\n## Changelog\n`);
  sections.push(`- [${packageName} ${toVersion} release notes](${changelogUrl})`);

  // Migration Notes
  sections.push(`\n## Migration Notes\n`);
  sections.push(
    `> _Generated by Kiln. Every breaking change is listed below with the file:line Kiln patched ` +
      `or flagged for human review._\n`
  );

  if (breakingChanges.length === 0 && patchResults.length === 0) {
    sections.push(
      `No breaking changes detected in the ${fromVersion} → ${toVersion} range. ` +
        `This upgrade should be safe to merge.`
    );
  } else {
    if (breakingChanges.length > 0) {
      sections.push(`### Breaking Changes Identified\n`);
      for (const bc of breakingChanges) {
        const hint = bc.migrationHint ? ` — _${bc.migrationHint}_` : "";
        const api = bc.apiSurface ? ` (\`${bc.apiSurface}\`)` : "";
        sections.push(`- ${bc.description}${api}${hint}`);
      }
    }

    if (patchResults.length > 0) {
      sections.push(`\n### Patches Applied\n`);
      const applied = patchResults.filter((r) => r.status === "applied");
      const flagged = patchResults.filter(
        (r) => r.status === "conflict" || r.status === "not-found"
      );
      const skipped = patchResults.filter((r) => r.status === "already-patched");

      if (applied.length > 0) {
        sections.push(`**Mechanically patched (${applied.length}):**\n`);
        for (const r of applied) sections.push(summarizePatch(r));
      }

      if (flagged.length > 0) {
        sections.push(`\n**⚠️ Needs human review (${flagged.length}):**\n`);
        for (const r of flagged) sections.push(summarizePatch(r));
      }

      if (skipped.length > 0) {
        sections.push(`\n**Already patched (${skipped.length}):**\n`);
        for (const r of skipped) sections.push(summarizePatch(r));
      }
    }
  }

  // Footer
  sections.push(
    `\n---\n_Opened by [Kiln](https://github.com/apps/kiln). ` +
      `Do not modify the Migration Notes section — it is auto-generated._`
  );

  return sections.join("\n");
}

function buildLabels(input: MigrationNotesInput): string[] {
  const labels = ["kiln", "dependencies"];
  const hasConflicts = input.patchResults.some(
    (r) => r.status === "conflict" || r.status === "not-found"
  );
  if (hasConflicts) labels.push("needs-human-review");
  if (input.breakingChanges.length > 0) labels.push("breaking-change");
  return labels;
}

/**
 * Validate that a PR description meets Kiln's invariants:
 * - Contains ≥1 changelog URL
 * - Names at least one breaking change or explicitly states none
 */
export function validatePrDescription(desc: PrDescription): {
  valid: boolean;
  violations: string[];
} {
  const violations: string[] = [];

  const hasChangelogUrl = /https?:\/\/\S+/.test(desc.body);
  if (!hasChangelogUrl) {
    violations.push("PR body must contain ≥1 changelog URL");
  }

  const hasMigrationNotes = desc.body.includes("## Migration Notes");
  if (!hasMigrationNotes) {
    violations.push("PR body must contain a '## Migration Notes' section");
  }

  const hasBranchPrefix = desc.branchName.startsWith("feat/kiln-");
  if (!hasBranchPrefix) {
    violations.push("Branch name must start with 'feat/kiln-'");
  }

  return { valid: violations.length === 0, violations };
}

// Re-export for tests
export { summarizePatch };

function slugify(s: string): string {
  return s.replace(/[^a-z0-9]/gi, "-").toLowerCase();
}

// Unused import elimination
export type { PatchResult };
