/**
 * Kiln Web — shared TypeScript types
 *
 * All wire types match the Kiln API contract.
 * Zod schemas live adjacent in lib/schemas.ts for validation at boundaries.
 */

// ─── Identity ─────────────────────────────────────────────────────────────────

/**
 * Authenticated caller. Resolved from Okta OIDC — never constructed from
 * email prefix or Slack/Okta user IDs.
 */
export interface AuthUser {
  /** Okta user ID (sub claim) */
  id: string;
  /** Display name from Okta profile */
  name: string;
  /** Verified email from Okta SCIM */
  email: string;
  /** Team IDs this user belongs to (resolved from Okta groups per request) */
  teamIds: string[];
  /** Whether the user has platform-wide visibility */
  isPlatformAdmin: boolean;
}

// ─── Team Configuration ───────────────────────────────────────────────────────

/** Target version policy determines which upstream releases Kiln acts on. */
export type TargetVersionPolicy = "latest-stable" | "lts" | "pinned";

/** PR grouping strategies — mirrors Renovate's groupName semantics. */
export type GroupingStrategy = "per-dep" | "per-family" | "per-release-window";

/**
 * A dep family pattern — e.g. "@aws-sdk/*" groups all @aws-sdk packages into
 * a single consolidated PR per release window.
 */
export interface DepFamilyPattern {
  /** Glob pattern matching package names (e.g. "@aws-sdk/*", "@types/*") */
  pattern: string;
  /** Human-readable label shown in Migration Notes */
  label: string;
}

/** Per-team Kiln configuration — scoped to a single team's DynamoDB partition. */
export interface TeamConfig {
  teamId: string;
  /** Display name (from Okta group) */
  teamName: string;
  /** Repos this team has configured Kiln to watch */
  watchedRepos: WatchedRepo[];
  /** How PRs are grouped */
  groupingStrategy: GroupingStrategy;
  /** Family patterns — used when groupingStrategy = "per-family" */
  familyPatterns: DepFamilyPattern[];
  /**
   * Release window for "per-release-window" grouping.
   * Cron expression (e.g. "0 9 * * 1" = every Monday at 9am UTC).
   */
  releaseWindowCron?: string;
  /** Target version policy */
  targetVersionPolicy: TargetVersionPolicy;
  /** Review SLA in days — Kiln pings the Slack channel if a PR exceeds this */
  reviewSlaDays: number;
  /** Slack channel ID for notifications (e.g. "C01234ABCDE") */
  slackChannelId?: string;
  /** Packages to never upgrade (exact names or globs) */
  skipList: string[];
  /** Created at ISO-8601 */
  createdAt: string;
  /** Last updated ISO-8601 */
  updatedAt: string;
}

/** A repository registered for Kiln monitoring. */
export interface WatchedRepo {
  /** GitHub owner/repo (e.g. "acme/my-app") */
  fullName: string;
  /** GitHub App installation ID scoped to this repo */
  installationId: number;
  /** Default branch (e.g. "main") */
  defaultBranch: string;
  /** Whether Kiln is active for this repo */
  enabled: boolean;
}

// ─── Kiln PRs ─────────────────────────────────────────────────────────────────

/** Status of a Kiln-authored PR. */
export type KilnPRStatus =
  | "open"
  | "merged"
  | "closed"
  | "flagged_needs_human";

/**
 * A breaking change identified by Kiln in the vendor changelog and applied
 * (or flagged) in the target codebase.
 */
export interface BreakingChange {
  /** Short description of the breaking change from the vendor changelog */
  description: string;
  /**
   * Whether Kiln applied a mechanical patch or flagged for human judgment.
   * "patched" means Kiln modified the file.
   * "flagged" means it needs human review (complex migration, forked dep, etc.)
   */
  resolution: "patched" | "flagged";
  /** Affected file relative to repo root */
  filePath: string;
  /** Line number(s) in the original (pre-patch) file */
  lineRange: { start: number; end: number };
  /** Vendor changelog URL citing this change */
  changelogUrl: string;
  /** Human-readable patch description written by Kiln */
  patchNote: string;
}

/** Unified Migration Notes section that every Kiln PR must include. */
export interface MigrationNotes {
  /** At least one vendor changelog URL — gate-checked */
  changelogUrls: string[];
  /** All breaking changes Kiln identified — empty means patch-only bump */
  breakingChanges: BreakingChange[];
  /** Packages included in this PR (≥1 for grouped PRs) */
  packages: PackageUpgrade[];
  /** Human-readable summary generated by Claude */
  summary: string;
}

/** A single package upgrade included in a Kiln PR. */
export interface PackageUpgrade {
  name: string;
  fromVersion: string;
  toVersion: string;
}

/** A Kiln-authored GitHub PR with migration notes. */
export interface KilnPR {
  id: string;
  /** GitHub PR number */
  prNumber: number;
  /** GitHub PR URL */
  prUrl: string;
  /** Repository this PR targets */
  repoFullName: string;
  /** Branch Kiln pushed to */
  headBranch: string;
  /** PR title generated by Kiln */
  title: string;
  status: KilnPRStatus;
  /** Whether Kiln's commits carry the GitHub Verified badge */
  isSigned: boolean;
  migrationNotes: MigrationNotes;
  /** ISO-8601 timestamp when Kiln opened the PR */
  openedAt: string;
  /** ISO-8601 timestamp when the PR was merged/closed, if applicable */
  closedAt?: string;
  /** Team that owns this PR */
  teamId: string;
  /** Grouping key (family pattern label, dep name, or window cron) */
  groupKey: string;
}

// ─── API Responses ────────────────────────────────────────────────────────────

export interface PaginatedResponse<T> {
  items: T[];
  nextCursor?: string;
  totalCount: number;
}

export interface ApiError {
  code: string;
  message: string;
  requestId: string;
}

// ─── Onboarding ───────────────────────────────────────────────────────────────

/** Steps in the GitHub App installation + Kiln team setup wizard. */
export type OnboardingStep =
  | "install-app"
  | "select-repos"
  | "configure-grouping"
  | "configure-notifications"
  | "review";

export interface OnboardingState {
  currentStep: OnboardingStep;
  githubInstallationId?: number;
  selectedRepos: WatchedRepo[];
  draftConfig: Partial<TeamConfig>;
}

// ─── Metrics ──────────────────────────────────────────────────────────────────

/** Team-level freshness metrics surfaced in the settings overview. */
export interface TeamMetrics {
  teamId: string;
  /** Median days from Kiln PR open to merged — target ≤7 */
  medianMergeDays: number | null;
  /** % of upstream releases that triggered a Kiln PR within 24h — target ≥90% */
  releaseTriggeredPct: number | null;
  /** Total open Kiln PRs */
  openPrCount: number;
  /** Total merged Kiln PRs */
  mergedPrCount: number;
  /** PRs flagged for human judgment (cannot be auto-patched) */
  flaggedPrCount: number;
  /** Computed over last N days */
  windowDays: number;
}
